apiVersion: apps/v1
kind: Deployment
metadata:
  name: nest-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nest-api
  template:
    metadata:
      labels:
        app: nest-api
    spec:
      containers:
        - name: nest-api
          image: sample-nest-api
          ports:
            - containerPort: 3000